package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	Reset   = "\033[0m"
	Red     = "\033[31m"
	Green   = "\033[32m"
	Yellow  = "\033[33m"
	Blue    = "\033[34m"
	Magenta = "\033[35m"
	Cyan    = "\033[36m"
	White   = "\033[37m"
	Bold    = "\033[1m"
)

var (
	deviceSerial string
	pointCount   int
	reportFile   *os.File
	mu           sync.Mutex
)

var sectionColors = map[string]string{
	"DEVICE IDENTITY":      Cyan,
	"OPERATING SYSTEM":     Green,
	"BUILD INFO":           Blue,
	"HARDWARE":             Yellow,
	"STORAGE":              Magenta,
	"GPU":                  Cyan,
	"NETWORK":              Blue,
	"TELEPHONY":            Green,
	"DISPLAY":              Magenta,
	"BATTERY":              Green,
	"SENSORS":              Yellow,
	"CAMERA":               Magenta,
	"SECURITY":             Red,
	"PERFORMANCE":          Cyan,
	"THERMAL":              Red,
	"AUDIO":                Blue,
	"SYSTEM":               Green,
	"NETWORKING ADVANCED":  Blue,
	"EXTRAS":               Cyan,
	"KERNEL DEEP":          Yellow,
	"HARDWARE DEEP":        Yellow,
	"NETWORK DEEP":         Blue,
	"SECURITY DEEP":        Red,
	"POWER DEEP":           Green,
	"PERFORMANCE DEEP":     Cyan,
}

func main() {
	args := os.Args
	reportPath := "android_audit_690_go.txt"
	if len(args) > 1 {
		reportPath = args[1]
	}

	fmt.Println()
	fmt.Println(Cyan + "======================================================================" + Reset)
	fmt.Println(Cyan + "           ANDROID TOTAL AUDIT REPORT (Go)" + Reset)
	fmt.Println(Cyan + "       HARDWARE & SOFTWARE DETAILED INVENTORY" + Reset)
	fmt.Println(Cyan + "======================================================================" + Reset)
	fmt.Println()

	if !checkADB() {
		os.Exit(1)
	}

	startTime := time.Now()

	var err error
	reportFile, err = os.Create(reportPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create report: %v\n", err)
		os.Exit(1)
	}
	defer reportFile.Close()

	reportFile.WriteString("ANDROID TOTAL AUDIT REPORT\n")
	reportFile.WriteString("Hardware & Software Detailed Inventory\n")
	reportFile.WriteString(fmt.Sprintf("Generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	reportFile.WriteString("Tool: ADB + Go\n\n")

	sectionHeader("DEVICE IDENTITY")
	deviceIdentity()

	sectionHeader("OPERATING SYSTEM")
	operatingSystem()

	sectionHeader("BUILD INFO")
	buildInfo()

	sectionHeader("HARDWARE")
	hardware()

	sectionHeader("STORAGE")
	storage()

	sectionHeader("GPU")
	gpu()

	sectionHeader("NETWORK")
	network()

	sectionHeader("TELEPHONY")
	telephony()

	sectionHeader("DISPLAY")
	display()

	sectionHeader("BATTERY")
	battery()

	sectionHeader("SENSORS")
	sensors()

	sectionHeader("CAMERA")
	camera()

	sectionHeader("SECURITY")
	security()

	sectionHeader("PERFORMANCE")
	performance()

	sectionHeader("THERMAL")
	thermal()

	sectionHeader("AUDIO")
	audio()

	sectionHeader("SYSTEM")
	systemInfo()

	sectionHeader("NETWORKING ADVANCED")
	networkingAdvanced()

	sectionHeader("EXTRAS")
	extras()

	sectionHeader("KERNEL DEEP")
	kernelDeep()

	sectionHeader("HARDWARE DEEP")
	hardwareDeep()

	sectionHeader("NETWORK DEEP")
	networkDeep()

	sectionHeader("SECURITY DEEP")
	securityDeep()

	sectionHeader("POWER DEEP")
	powerDeep()

	sectionHeader("PERFORMANCE DEEP")
	performanceDeep()

	duration := time.Since(startTime)

	fmt.Println()
	fmt.Println(Green + "======================================================================" + Reset)
	fmt.Printf(Green+"  Audit Complete: %d points in %.1fs\n"+Reset, pointCount, duration.Seconds())
	fmt.Printf(Green+"  Device: %s %s\n"+Reset, getProp("ro.product.manufacturer"), getProp("ro.product.model"))
	fmt.Printf(Green+"  SoC: %s\n"+Reset, detectSoC())
	fmt.Printf(Green+"  Report saved: %s\n"+Reset, reportPath)
	fmt.Println(Green + "======================================================================" + Reset)
	fmt.Println()

	reportFile.WriteString(fmt.Sprintf("\nAudit Complete: %d points in %.1fs\n", pointCount, duration.Seconds()))
	reportFile.WriteString(fmt.Sprintf("Device: %s %s\n", getProp("ro.product.manufacturer"), getProp("ro.product.model")))
	reportFile.WriteString(fmt.Sprintf("SoC: %s\n", detectSoC()))
	reportFile.WriteString("Generated by: ADB + Go\n")
}

func checkADB() bool {
	cmd := exec.Command("adb", "devices")
	out, err := cmd.Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, Red+"[!] ADB not found. Install Android platform tools.\n"+Reset)
		return false
	}
	re := regexp.MustCompile(`(.*?)\s+device$`)
	for _, line := range strings.Split(string(out), "\n") {
		matches := re.FindStringSubmatch(line)
		if len(matches) > 1 {
			deviceSerial = matches[1]
			fmt.Printf(Green+"[+] Device: %s\n\n"+Reset, deviceSerial)
			return true
		}
	}
	fmt.Fprintf(os.Stderr, Red+"[!] No Android device detected.\n"+Reset)
	return false
}

func adb(args ...string) string {
	fullArgs := []string{"-s", deviceSerial}
	fullArgs = append(fullArgs, args...)
	cmd := exec.Command("adb", fullArgs...)
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimRight(string(out), "\r\n ")
}

func getProp(key string) string {
	return adb("shell", "getprop", key)
}

func catFile(path string) string {
	return adb("shell", "cat", path)
}

func shellCmd(cmd string) string {
	return adb("shell", cmd)
}

func settingsGet(ns, key string) string {
	v := adb("shell", "settings", "get", ns, key)
	if v == "" || v == "null" {
		return "?"
	}
	return v
}

func detectSoC() string {
	platform := getProp("ro.board.platform")
	platform = strings.ToLower(platform)

	mtMatch := regexp.MustCompile(`^(mt\d+)`)
	socMatch := regexp.MustCompile(`^(sm\d+|msm\d+|sdm\d+)`)

	if m := mtMatch.FindStringSubmatch(platform); len(m) > 1 {
		switch m[1] {
		case "mt6789":
			return "MediaTek Helio G99 Ultra"
		case "mt6781":
			return "MediaTek Helio G96"
		case "mt6771":
			return "MediaTek Helio P60/P70"
		case "mt6768":
			return "MediaTek Helio G70/G80/G85"
		case "mt6765":
			return "MediaTek Helio G25/P35"
		case "mt6833":
			return "MediaTek Dimensity 700"
		case "mt6853":
			return "MediaTek Dimensity 720"
		case "mt6877":
			return "MediaTek Dimensity 900"
		case "mt6883":
			return "MediaTek Dimensity 1000"
		case "mt6891":
			return "MediaTek Dimensity 1100"
		case "mt6893":
			return "MediaTek Dimensity 1200"
		case "mt6983":
			return "MediaTek Dimensity 9000"
		case "mt6985":
			return "MediaTek Dimensity 9200"
		case "mt6989":
			return "MediaTek Dimensity 9300"
		default:
			return "MediaTek " + platform
		}
	}
	if s := socMatch.FindStringSubmatch(platform); len(s) > 1 {
		switch s[1] {
		case "sm8550", "sm8550-*":
			return "Qualcomm Snapdragon 8 Gen 2"
		case "sm8650":
			return "Qualcomm Snapdragon 8 Gen 3"
		case "sm8750":
			return "Qualcomm Snapdragon 8 Gen 4"
		case "sm8450", "sm8475":
			return "Qualcomm Snapdragon 8 Gen 1/+"
		case "sm8350", "sm8355":
			return "Qualcomm Snapdragon 888/+"
		case "sm7325":
			return "Qualcomm Snapdragon 778G"
		case "sdm865", "sdm870":
			return "Qualcomm Snapdragon 865/870"
		case "sdm855":
			return "Qualcomm Snapdragon 855/+"
		case "sdm845":
			return "Qualcomm Snapdragon 845"
		case "sdm835":
			return "Qualcomm Snapdragon 835"
		case "sdm660":
			return "Qualcomm Snapdragon 660"
		default:
			return "Qualcomm Snapdragon " + platform
		}
	}
	if strings.HasPrefix(platform, "sc") || strings.HasPrefix(platform, "t") {
		return "Unisoc/Spreadtrum " + platform
	}
	if strings.HasPrefix(platform, "exynos") {
		return "Samsung Exynos " + platform
	}
	if strings.HasPrefix(platform, "kirin") {
		return "HiSilicon Kirin " + platform
	}
	if strings.HasPrefix(platform, "rk") {
		return "Rockchip " + platform
	}
	if platform == "" {
		return "?" + "[N/A]"
	}
	return "Unknown SoC (" + platform + ")"
}

func colorForValue(val string) string {
	if val == "" || val == "?" || strings.Contains(val, "[N/A]") {
		return Red
	}
	lower := strings.ToLower(val)
	if strings.Contains(lower, "error") || strings.Contains(lower, "not") {
		return Yellow
	}
	return Green
}

func printPoint(section, desc, value string) {
	mu.Lock()
	defer mu.Unlock()

	if value == "" {
		value = "?"
	}
	color := colorForValue(value)
	shortVal := value
	if len(shortVal) > 150 {
		shortVal = shortVal[:150]
	}

	fmt.Printf("  "+Green+"[+]"+Reset+" "+White+"%s:"+Reset+" "+color+"%s"+Reset+"\n", desc, shortVal)
	reportFile.WriteString(fmt.Sprintf("  [+] %s: %s\n", desc, shortVal))
	pointCount++
}

func sectionHeader(name string) {
	color := sectionColors[name]
	if color == "" {
		color = Cyan
	}
	fmt.Println()
	fmt.Println(color + "==================================================================" + Reset)
	fmt.Println(color + "  " + name + Reset)
	fmt.Println(color + "==================================================================" + Reset)
	fmt.Println()
	reportFile.WriteString("\n==================================================================\n")
	reportFile.WriteString("  " + name + "\n")
	reportFile.WriteString("==================================================================\n\n")
}

// ============================================================
// SECTIONS
// ============================================================

func deviceIdentity() {
	props := []struct{ key, desc string }{
		{"ro.product.model", "Device Model"},
		{"ro.product.manufacturer", "Manufacturer"},
		{"ro.product.brand", "Brand"},
		{"ro.product.marketname", "Market Name"},
		{"ro.product.name", "Product Name"},
		{"ro.product.device", "Product Device"},
		{"ro.product.board", "Product Board"},
		{"ro.hardware", "Hardware"},
		{"ro.board.platform", "Platform/SoC"},
		{"ro.chipname", "Chipname"},
		{"ro.bootloader", "Bootloader"},
		{"ro.serialno", "Serial Number"},
		{"ro.boot.serialno", "Boot Serial"},
		{"ro.build.fingerprint", "Fingerprint"},
		{"ro.build.description", "Description"},
		{"persist.sys.locale", "Locale"},
		{"ro.product.locale.language", "Language"},
		{"ro.product.locale.region", "Region"},
		{"persist.sys.timezone", "Timezone"},
		{"ro.build.characteristics", "Characteristics"},
		{"ro.build.display.id", "Display ID"},
		{"ro.product.cpu.abi", "CPU ABI"},
		{"ro.product.cpu.abilist", "ABI List"},
		{"ro.product.cpu.abi2", "ABI2"},
	}
	for _, p := range props {
		printPoint("DEVICE IDENTITY", p.desc, getProp(p.key))
	}
}

func operatingSystem() {
	printPoint("OPERATING SYSTEM", "Android Version", getProp("ro.build.version.release"))
	printPoint("OPERATING SYSTEM", "API Level", getProp("ro.build.version.sdk"))
	printPoint("OPERATING SYSTEM", "Preview SDK", getProp("ro.build.version.preview_sdk"))
	printPoint("OPERATING SYSTEM", "Codename", getProp("ro.build.version.codename"))
	printPoint("OPERATING SYSTEM", "Incremental", getProp("ro.build.version.incremental"))
	printPoint("OPERATING SYSTEM", "Security Patch", getProp("ro.build.version.security_patch"))
	printPoint("OPERATING SYSTEM", "Vendor Security Patch", getProp("ro.vendor.build.security_patch"))
	printPoint("OPERATING SYSTEM", "Base OS", getProp("ro.build.version.base_os"))
	printPoint("OPERATING SYSTEM", "Build Type", getProp("ro.build.type"))
	printPoint("OPERATING SYSTEM", "Build Tags", getProp("ro.build.tags"))
	printPoint("OPERATING SYSTEM", "Build User", getProp("ro.build.user"))
	printPoint("OPERATING SYSTEM", "Build Host", getProp("ro.build.host"))
	printPoint("OPERATING SYSTEM", "Build Date UTC", getProp("ro.build.date.utc"))
	printPoint("OPERATING SYSTEM", "Build Date Full", getProp("ro.build.date"))
	printPoint("OPERATING SYSTEM", "Kernel Version", truncate(catFile("/proc/version"), 100))
	printPoint("OPERATING SYSTEM", "Uptime", extractUptime())
	printPoint("OPERATING SYSTEM", "Swappiness", catFile("/proc/sys/vm/swappiness"))
	printPoint("OPERATING SYSTEM", "Overcommit Ratio", catFile("/proc/sys/vm/overcommit_ratio"))
	printPoint("OPERATING SYSTEM", "Treble Supported", getProp("ro.treble.enabled"))
	printPoint("OPERATING SYSTEM", "AB Update", getProp("ro.build.ab_update"))
	printPoint("OPERATING SYSTEM", "Virtual AB", getProp("ro.virtual_ab.enabled"))
	printPoint("OPERATING SYSTEM", "VNDK Version", getProp("ro.vndk.version"))
	printPoint("OPERATING SYSTEM", "Hostname", catFile("/proc/sys/kernel/hostname"))
	printPoint("OPERATING SYSTEM", "File Max", catFile("/proc/sys/fs/file-max"))
	printPoint("OPERATING SYSTEM", "Max PID", catFile("/proc/sys/kernel/pid_max"))
}

func extractUptime() string {
	raw := catFile("/proc/uptime")
	if raw == "" {
		return "?"
	}
	parts := strings.Fields(raw)
	if len(parts) == 0 {
		return "?"
	}
	secs, err := strconv.ParseFloat(parts[0], 64)
	if err != nil {
		return raw
	}
	days := int(secs / 86400)
	hours := int((secs - float64(days*86400)) / 3600)
	mins := int((secs - float64(days*86400) - float64(hours*3600)) / 60)
	return fmt.Sprintf("%dd %dh %dm", days, hours, mins)
}

func truncate(s string, max int) string {
	if len(s) > max {
		return s[:max]
	}
	return s
}

func buildInfo() {
	props := []struct{ key, desc string }{
		{"ro.build.id", "Build ID"},
		{"ro.build.display.id", "Build Display ID"},
		{"ro.build.flavor", "Build Flavor"},
		{"ro.build.fingerprint", "Build Fingerprint"},
		{"ro.build.type", "Build Type"},
		{"ro.build.user", "Build User"},
		{"ro.build.host", "Build Host"},
		{"ro.build.date", "Build Date"},
		{"ro.build.date.utc", "Build Date UTC"},
		{"ro.build.version.incremental", "Build Incremental"},
		{"ro.build.version.release", "Version Release"},
		{"ro.build.version.sdk", "Version SDK"},
		{"ro.build.version.codename", "Version Codename"},
		{"ro.build.version.security_patch", "Security Patch"},
		{"ro.build.version.base_os", "Base OS"},
		{"ro.build.version.preview_sdk", "Preview SDK"},
		{"ro.build.characteristics", "Characteristics"},
		{"ro.board.platform", "Board Platform"},
		{"ro.boot.baseband", "Boot Baseband"},
		{"ro.boot.hardware", "Boot Hardware"},
		{"ro.boot.serialno", "Boot Serial"},
		{"ro.boot.verifiedbootstate", "Boot Verified State"},
		{"ro.build.tags", "Build Tags"},
		{"ro.build.version.release_names", "Release Names"},
		{"ro.build.version.all_codenames", "All Codenames"},
		{"ro.product.cpu.abilist", "ABI List"},
		{"ro.product.cpu.abi", "ABI"},
		{"ro.product.cpu.abi2", "ABI2"},
		{"ro.build.description", "Description"},
	}
	for _, p := range props {
		printPoint("BUILD INFO", p.desc, getProp(p.key))
	}
}

func hardware() {
	cpuInfo := catFile("/proc/cpuinfo")
	memInfo := catFile("/proc/meminfo")

	cpuCount := 0
	for _, line := range strings.Split(cpuInfo, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "processor") {
			cpuCount++
		}
	}

	printPoint("HARDWARE", "SoC Full Name", detectSoC())
	printPoint("HARDWARE", "CPU Cores", fmt.Sprintf("%d", cpuCount))
	printPoint("HARDWARE", "CPU Implementer", extractCPUInfo(cpuInfo, "CPU implementer"))
	printPoint("HARDWARE", "CPU Part", extractCPUInfo(cpuInfo, "CPU part"))
	printPoint("HARDWARE", "CPU Architecture", extractCPUInfo(cpuInfo, "CPU architecture"))
	printPoint("HARDWARE", "CPU Features", truncate(extractCPUInfo(cpuInfo, "Features"), 120))
	printPoint("HARDWARE", "CPU Hardware", extractCPUInfo(cpuInfo, "Hardware"))
	printPoint("HARDWARE", "CPU BogoMIPS", extractCPUInfo(cpuInfo, "BogoMIPS"))
	printPoint("HARDWARE", "CPU Revision", extractCPUInfo(cpuInfo, "CPU revision"))

	memTotal := extractMemInfo(memInfo, "MemTotal")
	printPoint("HARDWARE", "Total RAM", fmtKB(memTotal))
	printPoint("HARDWARE", "Available RAM", fmtKB(extractMemInfo(memInfo, "MemAvailable")))
	printPoint("HARDWARE", "Free RAM", fmtKB(extractMemInfo(memInfo, "MemFree")))
	printPoint("HARDWARE", "Cached RAM", fmtKB(extractMemInfo(memInfo, "Cached")))
	printPoint("HARDWARE", "Swap Total", fmtKB(extractMemInfo(memInfo, "SwapTotal")))
	printPoint("HARDWARE", "Swap Free", fmtKB(extractMemInfo(memInfo, "SwapFree")))
	printPoint("HARDWARE", "Dirty Pages", fmtKB(extractMemInfo(memInfo, "Dirty")))
	printPoint("HARDWARE", "AnonPages", fmtKB(extractMemInfo(memInfo, "AnonPages")))
	printPoint("HARDWARE", "Mapped", fmtKB(extractMemInfo(memInfo, "Mapped")))
	printPoint("HARDWARE", "Shmem", fmtKB(extractMemInfo(memInfo, "Shmem")))

	printPoint("HARDWARE", "Heap Start Size", getProp("dalvik.vm.heapstartsize"))
	printPoint("HARDWARE", "Heap Growth Limit", getProp("dalvik.vm.heapgrowthlimit"))
	printPoint("HARDWARE", "Heap Max Size", getProp("dalvik.vm.heapsize"))
	printPoint("HARDWARE", "Heap Min Free", getProp("dalvik.vm.heapminfree"))
	printPoint("HARDWARE", "Heap Utilization", getProp("dalvik.vm.heaptargetutilization"))
	printPoint("HARDWARE", "CPU Governor", catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"))
	printPoint("HARDWARE", "CPU Min Freq", catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq"))
	printPoint("HARDWARE", "CPU Max Freq", catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq"))
	printPoint("HARDWARE", "CPU Cur Freq", catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq"))
	printPoint("HARDWARE", "CPU Online", catFile("/sys/devices/system/cpu/online"))
	printPoint("HARDWARE", "CPU Present", catFile("/sys/devices/system/cpu/present"))
	printPoint("HARDWARE", "ABI List", getProp("ro.product.cpu.abilist"))
	printPoint("HARDWARE", "ABI List 32", getProp("ro.product.cpu.abilist32"))
	printPoint("HARDWARE", "ABI List 64", getProp("ro.product.cpu.abilist64"))
}

func extractCPUInfo(cpuInfo, key string) string {
	re := regexp.MustCompile(fmt.Sprintf(`(?m)^%s\s*:\s*(.+)$`, regexp.QuoteMeta(key)))
	matches := re.FindStringSubmatch(cpuInfo)
	if len(matches) > 1 {
		return strings.TrimSpace(matches[1])
	}
	return "?"
}

func extractMemInfo(memInfo, key string) string {
	re := regexp.MustCompile(fmt.Sprintf(`(?m)^%s:\s+(\d+)`, regexp.QuoteMeta(key)))
	matches := re.FindStringSubmatch(memInfo)
	if len(matches) > 1 {
		return matches[1]
	}
	return ""
}

func fmtKB(kbStr string) string {
	if kbStr == "" {
		return "?"
	}
	kb, err := strconv.Atoi(kbStr)
	if err != nil {
		return kbStr
	}
	mb := kb / 1024
	gb := mb / 1024
	if gb > 0 {
		return fmt.Sprintf("%dMB (%.1fGB)", mb, float64(mb)/1024.0)
	}
	return fmt.Sprintf("%dMB", mb)
}

func storage() {
	df := shellCmd("df -h")
	printPoint("STORAGE", "System Partition", extractDF(df, "/system", 1))
	printPoint("STORAGE", "Data Partition", extractDF(df, "/data ", 1))
	printPoint("STORAGE", "Cache Partition", extractDF(df, "/cache", 1))
	sdCard := "Not detected"
	if strings.Contains(catFile("/proc/mounts"), "sdcard") {
		sdCard = "Detected"
	}
	printPoint("STORAGE", "External SD Card", sdCard)

	// Auto-detect block device
	blkDev := "mmcblk0"
	mountInfo := catFile("/proc/mounts")
	for _, line := range strings.Split(mountInfo, "\n") {
		if strings.Contains(line, "/data ") && strings.HasPrefix(line, "/dev/block/") {
			parts := strings.Split(line, " ")
			if len(parts) > 0 {
				blkDev = strings.TrimPrefix(parts[0], "/dev/block/")
			}
			break
		}
	}

	mmcName := catFile("/sys/block/" + blkDev + "/device/name")
	mmcType := catFile("/sys/block/" + blkDev + "/device/type")
	ioSched := catFile("/sys/block/" + blkDev + "/queue/scheduler")
	ioRot := catFile("/sys/block/" + blkDev + "/queue/rotational")
	ioRA := catFile("/sys/block/" + blkDev + "/queue/read_ahead_kb")

	// UFS detection
	ufsV := shellCmd("cat /sys/devices/platform/soc/*/ufshcd*/name /sys/devices/platform/soc/*/ufs*/name 2>/dev/null")
	if len(ufsV) > 60 {
		ufsV = ufsV[:60]
	}
	ufsV = strings.TrimSpace(strings.ReplaceAll(ufsV, "\n", " "))
	if ufsV == "" {
		ufsCheck := shellCmd("ls /sys/bus/platform/drivers/ufshcd 2>/dev/null | head -c30")
		if ufsCheck != "" {
			ufsV = ufsCheck
		}
	}

	storageTypeProp := getProp("ro.boot.storage_type")
	storageLabel := "?"
	if mmcName != "" {
		if mmcType == "MMC" {
			storageLabel = "eMMC"
		} else {
			storageLabel = "? (" + mmcType + ")"
		}
	} else if ufsV != "" {
		storageLabel = "UFS"
	} else if storageTypeProp != "?" {
		storageLabel = storageTypeProp
	} else {
		nvmeName := catFile("/sys/block/nvme0n1/device/model")
		if nvmeName != "" {
			storageLabel = "NVMe"
		}
	}
	if mmcName == "" {
		mmcName = ufsV
	}

	printPoint("STORAGE", "Storage Type", storageLabel)
	printPoint("STORAGE", "Model/Name", ifEmpty(mmcName, "?"))
	printPoint("STORAGE", "MMC Type", ifEmpty(mmcType, "?"))
	printPoint("STORAGE", "I/O Scheduler", ifEmpty(ioSched, "?"))
	printPoint("STORAGE", "Read Ahead", ifEmpty(ioRA, "?")+" KB")
	rotStr := "?"
	if ioRot == "1" {
		rotStr = "HDD"
	} else if ioRot == "0" {
		rotStr = "SSD/eMMC/UFS"
	}
	printPoint("STORAGE", "Rotational", rotStr)
	printPoint("STORAGE", "F2FS Support", checkFS("f2fs"))
	printPoint("STORAGE", "EXT4 Support", checkFS("ext4"))
	printPoint("STORAGE", "Encryption Type", getProp("ro.crypto.type"))
	printPoint("STORAGE", "Encrypted", getProp("ro.crypto.state"))
	printPoint("STORAGE", "Kernel Version", truncate(catFile("/proc/version"), 80))
}

func extractDF(df, mount string, col int) string {
	for _, line := range strings.Split(df, "\n") {
		if strings.Contains(line, mount) {
			fields := strings.Fields(line)
			if len(fields) > col {
				return fields[col]
			}
		}
	}
	return "?"
}

func checkFS(fs string) string {
	if strings.Contains(catFile("/proc/filesystems"), fs) {
		return "Supported"
	}
	return "Not supported"
}

func gpu() {
	printPoint("GPU", "GPU Renderer", getProp("ro.hardware.gralloc"))
	printPoint("GPU", "OpenGL ES Version", getProp("ro.opengles.version"))
	printPoint("GPU", "Vulkan API", detectVulkan())
	printPoint("GPU", "EGL Config", getProp("ro.egl.config"))
	printPoint("GPU", "EGL HW", getProp("ro.hardware.egl"))
	printPoint("GPU", "HWUI Renderer", getProp("debug.hwui.renderer"))
	printPoint("GPU", "SF Vsync", getProp("debug.sf.disable_vsync"))

	// Adreno paths
	gpuClk := catFile("/sys/class/kgsl/kgsl-3d0/gpuclk")
	gpuMax := catFile("/sys/class/kgsl/kgsl-3d0/max_gpuclk")
	gpuBusy := catFile("/sys/class/kgsl/kgsl-3d0/gpu_busy_percentage")
	gpuGov := catFile("/sys/class/kgsl/kgsl-3d0/devfreq/governor")
	gpuTherm := catFile("/sys/class/kgsl/kgsl-3d0/thermal_pwrlevel")
	gpuAvail := catFile("/sys/class/kgsl/kgsl-3d0/gpu_available_frequencies")

	// Mali paths
	if gpuClk == "" || gpuGov == "" {
		maliDev := shellCmd("ls -d /sys/devices/platform/*mali* /sys/devices/platform/*.mali 2>/dev/null | head -1")
		maliDev = strings.TrimSpace(maliDev)
		if maliDev != "" && !strings.Contains(maliDev, "No such") {
			if gpuClk == "" {
				for _, p := range []string{"/frequency", "/cur_freq", "/clock"} {
					if v := catFile(maliDev + p); v != "" {
						gpuClk = v
						break
					}
				}
			}
			if gpuMax == "" {
				gpuMax = catFile(maliDev + "/max_freq")
			}
			if gpuGov == "" {
				for _, p := range []string{"/dvfs_governor", "/governor"} {
					if v := catFile(maliDev + p); v != "" {
						gpuGov = v
						break
					}
				}
			}
			if gpuBusy == "" {
				for _, p := range []string{"/utilization", "/load"} {
					if v := catFile(maliDev + p); v != "" {
						gpuBusy = v
						break
					}
				}
			}
			if gpuAvail == "" {
				gpuAvail = catFile(maliDev + "/available_frequencies")
			}
		}
		// /sys/kernel/gpu fallback
		if gpuClk == "" {
			gpuClk = catFile("/sys/kernel/gpu/gpu_cur_freq")
		}
		if gpuMax == "" {
			gpuMax = catFile("/sys/kernel/gpu/gpu_max_freq")
		}
		if gpuGov == "" {
			gpuGov = catFile("/sys/kernel/gpu/gpu_governor")
		}
		if gpuBusy == "" {
			gpuBusy = catFile("/sys/kernel/gpu/gpu_busy")
		}
		// GPU thermal zone
		if gpuTherm == "" {
			for i := 0; i < 20; i++ {
				ttype := catFile(fmt.Sprintf("/sys/class/thermal/thermal_zone%d/type", i))
				if strings.Contains(strings.ToLower(ttype), "gpu") {
					gpuTherm = catFile(fmt.Sprintf("/sys/class/thermal/thermal_zone%d/temp", i))
					if temp, err := strconv.Atoi(strings.TrimSpace(gpuTherm)); err == nil {
						gpuTherm = fmt.Sprintf("%.1fC", float64(temp)/1000.0)
					}
					break
				}
			}
		}
	}

	// Governor sanity - reject CPU governors
	knownGPU := []string{"mali", "dvfs", "performance", "powersave", "simple_ondemand", "cooperative"}
	if gpuGov != "" {
		isGPU := false
		gpuGovLower := strings.ToLower(gpuGov)
		for _, kg := range knownGPU {
			if strings.Contains(gpuGovLower, kg) {
				isGPU = true
				break
			}
		}
		if !isGPU {
			gpuGov = ""
		}
	}

	printPoint("GPU", "GPU Cur Freq", ifEmpty(gpuClk, "?"))
	printPoint("GPU", "GPU Max Freq", ifEmpty(gpuMax, "?"))
	printPoint("GPU", "GPU Min Freq", catFile("/sys/class/kgsl/kgsl-3d0/min_gpuclk"))
	printPoint("GPU", "GPU Busy", ifEmpty(gpuBusy, "?"))
	printPoint("GPU", "GPU Governor", ifEmpty(gpuGov, "?"))
	printPoint("GPU", "GPU Thermal Level", ifEmpty(gpuTherm, "?"))
	printPoint("GPU", "GPU Avail Freqs", ifEmpty(gpuAvail, "?"))
	printPoint("GPU", "OpenCL Support", checkFile("/system/vendor/lib/libOpenCL.so"))
	printPoint("GPU", "Gralloc Version", getProp("ro.hardware.gralloc"))
}

func checkFile(path string) string {
	r := shellCmd("ls " + path)
	if strings.Contains(r, "No such") || r == "" {
		return "Not found"
	}
	return "Supported"
}

func detectVulkan() string {
	support := getProp("ro.hardware.vulkan")
	apiVer := getProp("ro.vulkan.api")
	level := getProp("ro.vulkan.level")
	parts := []string{}
	if support != "?" {
		parts = append(parts, "Support: "+support)
	}
	if apiVer != "?" {
		parts = append(parts, "API: "+apiVer)
	}
	if level != "?" {
		parts = append(parts, "Level: "+level)
	}
	lib := shellCmd("ls /system/lib64/libvulkan.so /vendor/lib64/libvulkan.so /system/lib/libvulkan.so")
	if !strings.Contains(lib, "No such") && lib != "" {
		parts = append(parts, "libvulkan: present")
	}
	rm := shellCmd("dumpsys media.resource_manager | head -20 | grep -i vulkan")
	if rm != "" {
		if len(rm) > 60 {
			rm = rm[:60]
		}
		parts = append(parts, "ResourceMgr: "+strings.TrimSpace(rm))
	}
	if len(parts) == 0 {
		return "Not detected"
	}
	return strings.Join(parts, " | ")
}

func listDir(path string) string {
	return shellCmd("ls " + path + " 2>/dev/null")
}

func kernelDeep() {
	printPoint("KERNEL DEEP", "Kernel Version", truncate(catFile("/proc/version"), 150))
	printPoint("KERNEL DEEP", "Kernel Cmdline", truncate(catFile("/proc/cmdline"), 200))
	printPoint("KERNEL DEEP", "Kernel Modules", truncate(shellCmd("lsmod 2>/dev/null || cat /proc/modules"), 200))
	modCount := len(strings.Split(strings.TrimSpace(shellCmd("lsmod 2>/dev/null | tail -n +2 || cat /proc/modules")), "\n"))
	printPoint("KERNEL DEEP", "Module Count", fmt.Sprintf("%d", modCount))
	printPoint("KERNEL DEEP", "Interrupts Count", fmt.Sprintf("%d", len(strings.Split(strings.TrimSpace(catFile("/proc/interrupts")), "\n"))))
	printPoint("KERNEL DEEP", "CPU Online", catFile("/sys/devices/system/cpu/online"))
	printPoint("KERNEL DEEP", "CPU Present", catFile("/sys/devices/system/cpu/present"))
	printPoint("KERNEL DEEP", "CPU Possible", catFile("/sys/devices/system/cpu/possible"))
	printPoint("KERNEL DEEP", "IP Forwarding", catFile("/proc/sys/net/ipv4/ip_forward"))
	printPoint("KERNEL DEEP", "File Max", catFile("/proc/sys/fs/file-max"))
	fileNr := strings.Fields(catFile("/proc/sys/fs/file-nr"))
	if len(fileNr) > 0 {
		printPoint("KERNEL DEEP", "File Used", fileNr[0])
	}
	printPoint("KERNEL DEEP", "OsRelease", strings.TrimSpace(catFile("/proc/sys/kernel/ostype")+" "+catFile("/proc/sys/kernel/osrelease")))
	printPoint("KERNEL DEEP", "Hostname", catFile("/proc/sys/kernel/hostname"))
	printPoint("KERNEL DEEP", "Panic Timeout", catFile("/proc/sys/kernel/panic"))
	printPoint("KERNEL DEEP", "Panic On Oops", catFile("/proc/sys/kernel/panic_on_oops"))
	printPoint("KERNEL DEEP", "Printk Level", catFile("/proc/sys/kernel/printk"))
	printPoint("KERNEL DEEP", "Randomize VA", catFile("/proc/sys/kernel/randomize_va_space"))
	printPoint("KERNEL DEEP", "VM Max Map Count", catFile("/proc/sys/vm/max_map_count"))
	printPoint("KERNEL DEEP", "VM Laptop Mode", catFile("/proc/sys/vm/laptop_mode"))
	printPoint("KERNEL DEEP", "VM OOM Kill", catFile("/proc/sys/vm/oom_kill_allocating_task"))
	printPoint("KERNEL DEEP", "VM Panic OOM", catFile("/proc/sys/vm/panic_on_oom"))
	printPoint("KERNEL DEEP", "Iomem (top)", truncate(shellCmd("cat /proc/iomem 2>/dev/null | head -5"), 150))
}

func hardwareDeep() {
	// CPU topology - use 'cat' on each file via shell
	clusterIDs := shellCmd("for f in /sys/devices/system/cpu/cpu*/topology/cluster_id; do cat $f 2>/dev/null; done")
	printPoint("HARDWARE DEEP", "CPU Clusters", truncate(strings.ReplaceAll(strings.TrimSpace(clusterIDs), "\n", ","), 30))
	printPoint("HARDWARE DEEP", "Core Siblings", catFile("/sys/devices/system/cpu/cpu0/topology/core_siblings_list"))
	printPoint("HARDWARE DEEP", "Thread Siblings", catFile("/sys/devices/system/cpu/cpu0/topology/thread_siblings_list"))

	// Cache
	cacheStr := ""
	for i := 0; i < 4; i++ {
		ct := catFile(fmt.Sprintf("/sys/devices/system/cpu/cpu0/cache/index%d/type", i))
		cs := catFile(fmt.Sprintf("/sys/devices/system/cpu/cpu0/cache/index%d/size", i))
		if ct != "" && cs != "" {
			cacheStr += ct + ":" + cs + " "
		}
	}
	printPoint("HARDWARE DEEP", "CPU Cache", ifEmpty(cacheStr, "?"))

	printPoint("HARDWARE DEEP", "GPIO List", truncate(listDir("/sys/class/gpio"), 80))
	printPoint("HARDWARE DEEP", "I2C Devices", truncate(listDir("/sys/bus/i2c/devices"), 120))
	printPoint("HARDWARE DEEP", "DMA Channels", truncate(listDir("/sys/class/dma"), 80))
	regCount := len(strings.Fields(listDir("/sys/class/regulator")))
	printPoint("HARDWARE DEEP", "Regulators", fmt.Sprintf("%d", regCount))
	psCount := len(strings.Fields(listDir("/sys/class/power_supply")))
	printPoint("HARDWARE DEEP", "Power Supplies", fmt.Sprintf("%d", psCount))
	psList := listDir("/sys/class/power_supply")
	printPoint("HARDWARE DEEP", "Power Supply List", truncate(psList, 100))

	// Thermal types
	thermalTypes := shellCmd("for f in /sys/class/thermal/thermal_zone*/type; do echo -n \"$(cat $f 2>/dev/null) \"; done")
	printPoint("HARDWARE DEEP", "Thermal Zone Types", truncate(thermalTypes, 150))

	printPoint("HARDWARE DEEP", "Sound Cards", truncate(shellCmd("cat /proc/asound/cards 2>/dev/null"), 150))
	inputCount := len(strings.Split(strings.TrimSpace(shellCmd("cat /proc/bus/input/devices 2>/dev/null | grep 'N: Name'")), "\n"))
	printPoint("HARDWARE DEEP", "Input Devices", fmt.Sprintf("%d", inputCount))
	inputNames := shellCmd("cat /proc/bus/input/devices 2>/dev/null | grep 'N: Name' | sed 's/.*Name=\"//;s/\"//'")
	printPoint("HARDWARE DEEP", "Input Device Names", truncate(strings.ReplaceAll(strings.TrimSpace(inputNames), "\n", ","), 200))

	printPoint("HARDWARE DEEP", "Misc Devices", truncate(listDir("/sys/class/misc"), 120))
	printPoint("HARDWARE DEEP", "RTC Devices", truncate(listDir("/sys/class/rtc"), 60))
	printPoint("HARDWARE DEEP", "Video4Linux", fmt.Sprintf("%d", len(strings.Fields(listDir("/sys/class/video4linux")))))
	printPoint("HARDWARE DEEP", "Framebuffers", truncate(listDir("/sys/class/graphics"), 80))
	printPoint("HARDWARE DEEP", "Device Tree", truncate(listDir("/proc/device-tree"), 150))
	printPoint("HARDWARE DEEP", "Firmware Nodes", truncate(listDir("/sys/firmware"), 80))
}

func networkDeep() {
	printPoint("NETWORK DEEP", "Socket Stats", truncate(catFile("/proc/net/sockstat"), 150))
	printPoint("NETWORK DEEP", "Socket Stats6", truncate(catFile("/proc/net/sockstat6"), 120))
	ctCount := len(strings.Split(strings.TrimSpace(catFile("/proc/net/nf_conntrack")), "\n"))
	if ctCount <= 1 {
		ctCountStr := catFile("/proc/sys/net/netfilter/nf_conntrack_count")
		if ctCountStr != "" {
			printPoint("NETWORK DEEP", "ConnTrack Count", ctCountStr)
		}
	} else {
		printPoint("NETWORK DEEP", "ConnTrack Count", fmt.Sprintf("%d", ctCount))
	}
	printPoint("NETWORK DEEP", "ConnTrack Max", catFile("/proc/sys/net/netfilter/nf_conntrack_max"))
	iptRules := len(strings.Split(strings.TrimSpace(shellCmd("iptables -L 2>/dev/null")), "\n"))
	printPoint("NETWORK DEEP", "IPTables Lines", fmt.Sprintf("%d", iptRules))
	printPoint("NETWORK DEEP", "IPTables Summary", truncate(shellCmd("iptables -L 2>/dev/null | head -20"), 200))
	ip6Rules := len(strings.Split(strings.TrimSpace(shellCmd("ip6tables -L 2>/dev/null")), "\n"))
	printPoint("NETWORK DEEP", "IPv6 Rules", fmt.Sprintf("%d", ip6Rules))
	arpCount := len(strings.Split(strings.TrimSpace(shellCmd("cat /proc/net/arp | grep '0x'")), "\n"))
	printPoint("NETWORK DEEP", "ARP Entries", fmt.Sprintf("%d", arpCount))
	neighCount := len(strings.Fields(shellCmd("ip neigh 2>/dev/null")))
	printPoint("NETWORK DEEP", "IP Neighbors", fmt.Sprintf("%d", neighCount))
	printPoint("NETWORK DEEP", "Wireless Reg", truncate(shellCmd("iw reg get 2>/dev/null"), 80))
	netDevs := listDir("/sys/class/net")
	printPoint("NETWORK DEEP", "Net Devices", truncate(netDevs, 100))
	printPoint("NETWORK DEEP", "TCP Mem", catFile("/proc/sys/net/ipv4/tcp_mem"))
	printPoint("NETWORK DEEP", "UDP Mem", catFile("/proc/sys/net/ipv4/udp_mem"))
	printPoint("NETWORK DEEP", "TCP Timestamps", catFile("/proc/sys/net/ipv4/tcp_timestamps"))
	printPoint("NETWORK DEEP", "TCP Window Scale", catFile("/proc/sys/net/ipv4/tcp_window_scaling"))
	printPoint("NETWORK DEEP", "TCP MTU Probing", catFile("/proc/sys/net/ipv4/tcp_mtu_probing"))
	printPoint("NETWORK DEEP", "TCP Congestion Ctrl", catFile("/proc/sys/net/ipv4/tcp_congestion_control"))
	printPoint("NETWORK DEEP", "TCP Avail CC", truncate(catFile("/proc/sys/net/ipv4/tcp_available_congestion_control"), 80))
	printPoint("NETWORK DEEP", "TCP Fast Open", catFile("/proc/sys/net/ipv4/tcp_fastopen"))
}

func securityDeep() {
	printPoint("SECURITY DEEP", "SELinux Enforce", shellCmd("getenforce 2>/dev/null"))
	printPoint("SECURITY DEEP", "SELinux Loaded", catFile("/sys/fs/selinux/enforce"))
	selinuxBools := shellCmd("getsebool -a 2>/dev/null")
	if selinuxBools != "" {
		printPoint("SECURITY DEEP", "SELinux Booleans", truncate(strings.ReplaceAll(strings.TrimSpace(selinuxBools), "\n", ", "), 200))
	}
	printPoint("SECURITY DEEP", "SELinux AVC Stats", truncate(shellCmd("cat /sys/fs/selinux/avc/cache_stats 2>/dev/null | head -5"), 150))
	printPoint("SECURITY DEEP", "DM-Verity", getProp("ro.boot.veritymode"))
	printPoint("SECURITY DEEP", "AVB Version", getProp("ro.boot.avb_version"))
	keyCount := len(strings.Split(strings.TrimSpace(shellCmd("cat /proc/keys 2>/dev/null")), "\n"))
	printPoint("SECURITY DEEP", "Keyring Keys", fmt.Sprintf("%d", keyCount))
	printPoint("SECURITY DEEP", "Keyring (top)", truncate(shellCmd("cat /proc/keys 2>/dev/null | head -5"), 150))
	printPoint("SECURITY DEEP", "TEE Device", truncate(shellCmd("ls /dev/tee* 2>/dev/null"), 60))
	printPoint("SECURITY DEEP", "Keystore Type", getProp("ro.keystore.type"))
	printPoint("SECURITY DEEP", "Keymaster", getProp("ro.hardware.keystore"))
	printPoint("SECURITY DEEP", "GateKeeper", getProp("ro.hardware.gatekeeper"))
	printPoint("SECURITY DEEP", "FBE Enabled", getProp("ro.crypto.fbe"))
	printPoint("SECURITY DEEP", "Widevine Level", getProp("ro.widevine.level"))
	printPoint("SECURITY DEEP", "DRM Enabled", getProp("ro.drm.enabled"))
	printPoint("SECURITY DEEP", "KNOX Version", getProp("ro.security.knox.vers"))
	printPoint("SECURITY DEEP", "Fingerprint HAL", getProp("ro.hardware.fingerprint"))
	printPoint("SECURITY DEEP", "Face Unlock", getProp("ro.faceunlock.enabled"))
}

func powerDeep() {
	printPoint("POWER DEEP", "Wakeup Sources", truncate(shellCmd("cat /sys/kernel/debug/wakeup_sources 2>/dev/null | head -10"), 200))
	wakeCount := len(strings.Split(strings.TrimSpace(shellCmd("cat /sys/kernel/debug/wakeup_sources 2>/dev/null")), "\n"))
	printPoint("POWER DEEP", "Wakeup Count", fmt.Sprintf("%d", wakeCount))
	printPoint("POWER DEEP", "Suspend Stats", truncate(shellCmd("cat /sys/kernel/debug/suspend_stats 2>/dev/null | head -10"), 200))
	printPoint("POWER DEEP", "CPUIDLE Driver", catFile("/sys/devices/system/cpu/cpuidle/current_driver"))
	printPoint("POWER DEEP", "CPUIDLE Governor", catFile("/sys/devices/system/cpu/cpuidle/current_governor_ro"))

	cpuidleStates := ""
	for i := 0; i < 5; i++ {
		sname := catFile(fmt.Sprintf("/sys/devices/system/cpu/cpu0/cpuidle/state%d/name", i))
		slat := catFile(fmt.Sprintf("/sys/devices/system/cpu/cpu0/cpuidle/state%d/latency", i))
		if sname != "" {
			cpuidleStates += sname + "(" + slat + "us) "
		}
	}
	printPoint("POWER DEEP", "CPUIDLE States", ifEmpty(cpuidleStates, "?"))

	printPoint("POWER DEEP", "Max CPU Freq", catFile("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq"))
	printPoint("POWER DEEP", "Min CPU Freq", catFile("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq"))
	printPoint("POWER DEEP", "Avail Freqs", truncate(catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies"), 120))
	printPoint("POWER DEEP", "Avail Governors", truncate(catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors"), 120))
	printPoint("POWER DEEP", "Battery Capacity", catFile("/sys/class/power_supply/battery/capacity")+"%")
	printPoint("POWER DEEP", "Battery Health", catFile("/sys/class/power_supply/battery/health"))
	printPoint("POWER DEEP", "Battery Tech", catFile("/sys/class/power_supply/battery/technology"))
	printPoint("POWER DEEP", "Battery Temp", catFile("/sys/class/power_supply/battery/temp"))
	printPoint("POWER DEEP", "Battery Voltage", catFile("/sys/class/power_supply/battery/voltage_now")+"uV")
	printPoint("POWER DEEP", "Battery Current", catFile("/sys/class/power_supply/battery/current_now")+"uA")
}

func performanceDeep() {
	printPoint("PERF DEEP", "Binder State", truncate(shellCmd("cat /proc/binder/state 2>/dev/null | head -10"), 200))
	binderProcs := len(strings.Split(strings.TrimSpace(shellCmd("cat /proc/binder/proc 2>/dev/null")), "\n"))
	printPoint("PERF DEEP", "Binder Procs", fmt.Sprintf("%d", binderProcs))
	printPoint("PERF DEEP", "Ftrace Enabled", catFile("/sys/kernel/tracing/tracing_on"))
	printPoint("PERF DEEP", "Ftrace Buffer", catFile("/sys/kernel/tracing/buffer_size_kb")+"KB")
	printPoint("PERF DEEP", "Perf Events", truncate(shellCmd("ls /sys/bus/event_source/devices/ 2>/dev/null"), 80))
	printPoint("PERF DEEP", "ZRAM Algorithm", catFile("/sys/block/zram0/comp_algorithm"))
	printPoint("PERF DEEP", "ZRAM Disk Size", truncate(shellCmd("cat /sys/block/zram0/disksize 2>/dev/null | awk '{x=$1; if(x>1024) print x/1024 \"MB\"; else print x \"KB\"}'"), 20))
	printPoint("PERF DEEP", "Sched Features", truncate(shellCmd("cat /sys/kernel/debug/sched_features 2>/dev/null"), 100))
	printPoint("PERF DEEP", "Sched Wakeup Gran", catFile("/proc/sys/kernel/sched_wakeup_granularity_ns"))
	printPoint("PERF DEEP", "Sched Min Granularity", catFile("/proc/sys/kernel/sched_min_granularity_ns"))
	printPoint("PERF DEEP", "Sched Latency", catFile("/proc/sys/kernel/sched_latency_ns"))
	printPoint("PERF DEEP", "Sched Migration Cost", catFile("/proc/sys/kernel/sched_migration_cost_ns"))
	printPoint("PERF DEEP", "PID Max", catFile("/proc/sys/kernel/pid_max"))
	printPoint("PERF DEEP", "Threads Max", catFile("/proc/sys/kernel/threads-max"))
	procCount := len(strings.Split(strings.TrimSpace(shellCmd("ps 2>/dev/null")), "\n"))
	printPoint("PERF DEEP", "Process Count", fmt.Sprintf("%d", procCount))
}

func network() {
	wifiOut := shellCmd("dumpsys wifi")
	imei := shellCmd("service call iphonesubinfo 1")
	digits := regexp.MustCompile(`\d{14,}`).FindString(imei)
	if digits == "" {
		digits = "Restricted"
	}
	printPoint("NETWORK", "IMEI", digits)
	printPoint("NETWORK", "WiFi SSID", extractWifiField(wifiOut, "SSID:", `SSID:\s*"([^"]*)"`))
	printPoint("NETWORK", "WiFi BSSID", extractWifiField(wifiOut, "BSSID:", `BSSID:\s*([0-9a-fA-F:]{17})`))
	printPoint("NETWORK", "WiFi MAC", extractWifiField(wifiOut, "MAC:", `MAC:\s*([0-9a-fA-F:]{17})`))
	printPoint("NETWORK", "IP Address", extractIPAddr())
	printPoint("NETWORK", "Gateway", extractGateway())
	printPoint("NETWORK", "DNS Servers", getProp("net.dns1")+" "+getProp("net.dns2"))
	printPoint("NETWORK", "Bluetooth Name", settingsGet("secure", "bluetooth_name"))
	printPoint("NETWORK", "Bluetooth MAC", settingsGet("secure", "bluetooth_address"))
	printPoint("NETWORK", "Bluetooth State", settingsGet("global", "bluetooth_on"))
	printPoint("NETWORK", "Carrier", getProp("gsm.sim.operator.alpha"))
	printPoint("NETWORK", "Network Operator", getProp("gsm.operator.alpha"))
	printPoint("NETWORK", "Baseband", getProp("gsm.version.baseband"))
	printPoint("NETWORK", "Data Roaming", settingsGet("global", "data_roaming"))
	printPoint("NETWORK", "Mobile Data", settingsGet("global", "mobile_data"))
	printPoint("NETWORK", "HTTP Proxy", settingsGet("global", "http_proxy"))
	printPoint("NETWORK", "WiFi Interface", getProp("wifi.interface"))
	printPoint("NETWORK", "DHCP Server", getProp("dhcp.wlan0.server"))
	printPoint("NETWORK", "DHCP Gateway", getProp("dhcp.wlan0.gateway"))
	printPoint("NETWORK", "DHCP DNS1", getProp("dhcp.wlan0.dns1"))
	printPoint("NETWORK", "DHCP DNS2", getProp("dhcp.wlan0.dns2"))
	printPoint("NETWORK", "DHCP Lease", getProp("dhcp.wlan0.leasetime"))
	printPoint("NETWORK", "DHCP Mask", getProp("dhcp.wlan0.mask"))
}

func extractWifiField(out, field, pattern string) string {
	re := regexp.MustCompile(pattern)
	for _, line := range strings.Split(out, "\n") {
		if strings.Contains(line, field) {
			matches := re.FindStringSubmatch(line)
			if len(matches) > 1 {
				return matches[1]
			}
		}
	}
	return "?"
}

func extractIPAddr() string {
	ip := shellCmd("ip addr show wlan0")
	re := regexp.MustCompile(`inet\s+(\d+\.\d+\.\d+\.\d+)`)
	matches := re.FindStringSubmatch(ip)
	if len(matches) > 1 {
		return matches[1]
	}
	return "?"
}

func extractGateway() string {
	route := shellCmd("ip route show table 0")
	re := regexp.MustCompile(`default\s+via\s+(\d+\.\d+\.\d+\.\d+)`)
	matches := re.FindStringSubmatch(route)
	if len(matches) > 1 {
		return matches[1]
	}
	return getProp("dhcp.wlan0.gateway")
}

func telephony() {
	// Clean network type - filter "Unknown"
	netTypeRaw := getProp("gsm.network.type")
	netTypes := []string{}
	for _, t := range strings.Split(netTypeRaw, ",") {
		t = strings.TrimSpace(t)
		if t != "" && !strings.EqualFold(t, "unknown") {
			netTypes = append(netTypes, t)
		}
	}
	netType := netTypeRaw
	if len(netTypes) > 0 {
		netType = strings.Join(netTypes, ",")
	}

	printPoint("TELEPHONY", "Network Type", netType)
	printPoint("TELEPHONY", "Operator", getProp("gsm.operator.alpha"))
	printPoint("TELEPHONY", "SIM Operator", getProp("gsm.sim.operator.alpha"))
	printPoint("TELEPHONY", "SIM State", getProp("gsm.sim.state"))
	printPoint("TELEPHONY", "MCC/MNC", getProp("gsm.operator.numeric"))
	printPoint("TELEPHONY", "Roaming", getProp("gsm.operator.isroaming"))
	printPoint("TELEPHONY", "Data State", getProp("gsm.data.state"))
	printPoint("TELEPHONY", "Phone Type", getProp("gsm.current.phone-type"))
	printPoint("TELEPHONY", "SIM Count", getProp("ro.multisim.simcount"))
	printPoint("TELEPHONY", "DSDA/DSDS", getProp("persist.radio.multisim.config"))
	printPoint("TELEPHONY", "SIM2 Operator", getProp("gsm.sim.operator.alpha_1"))
	printPoint("TELEPHONY", "Call State", getProp("gsm.call.state"))
	printPoint("TELEPHONY", "NR State", getProp("gsm.nr.state"))
	printPoint("TELEPHONY", "LTE EARFCN", getProp("gsm.lte.earfcn"))

	// VoLTE from multiple props
	volteProps := []string{"persist.dbg.volte_avail", "persist.sys.ctl.volte", "persist.radio.volte_enabled",
		"persist.volte_enabled", "ro.volte.enabled", "gsm.sim.volte_available"}
	volte := getFirstProp(volteProps)
	tr := shellCmd("dumpsys telephony.registry")
	if strings.Contains(strings.ToLower(tr), "volte") && strings.Contains(strings.ToLower(tr), "true") {
		if volte == "?" {
			volte = "Enabled"
		}
	}
	printPoint("TELEPHONY", "VoLTE", volte)

	// VoNR
	vonrProps := []string{"persist.dbg.vonr_avail", "persist.radio.nr_voice_avail", "ro.vonr.enabled"}
	vonr := getFirstProp(vonrProps)
	if strings.Contains(strings.ToLower(tr), "vonr") && strings.Contains(strings.ToLower(tr), "true") {
		if vonr == "?" {
			vonr = "Enabled (NR)"
		}
	}
	printPoint("TELEPHONY", "VoNR", vonr)

	// VoWiFi
	vowifiProps := []string{"persist.dbg.wfc_avail", "persist.radio.wifi_call_avail",
		"persist.sys.ctl.vowifi", "ro.vowifi.enabled"}
	vowifi := getFirstProp(vowifiProps)
	printPoint("TELEPHONY", "VoWiFi", vowifi)

	// IMS
	ims := shellCmd("dumpsys ims")
	imsStatus := "Not registered"
	if strings.Contains(strings.ToLower(ims), "registered") {
		imsStatus = "Registered"
	}
	printPoint("TELEPHONY", "IMS Registration", imsStatus)
}

func display() {
	wmSize := strings.TrimPrefix(shellCmd("wm size"), "Physical size: ")
	wmDensity := strings.TrimPrefix(shellCmd("wm density"), "Physical density: ")
	printPoint("DISPLAY", "Resolution", strings.TrimSpace(wmSize))
	printPoint("DISPLAY", "Density", strings.TrimSpace(wmDensity)+"dpi")
	printPoint("DISPLAY", "LCD Density", getProp("ro.sf.lcd_density"))
	printPoint("DISPLAY", "SF HW", getProp("debug.sf.hw"))
	printPoint("DISPLAY", "VSync", getProp("debug.sf.disable_vsync"))
	printPoint("DISPLAY", "HDR Support", detectHDR())
	printPoint("DISPLAY", "Brightness", settingsGet("system", "screen_brightness"))
	printPoint("DISPLAY", "Auto Brightness", settingsGet("system", "screen_brightness_mode"))
	printPoint("DISPLAY", "Screen Off Timeout", settingsGet("system", "screen_off_timeout"))
	printPoint("DISPLAY", "Color Mode", getProp("persist.sys.sf.color_mode"))
	printPoint("DISPLAY", "HW Composer", getProp("ro.hardware.hwcomposer"))
	printPoint("DISPLAY", "Night Mode", settingsGet("secure", "night_display_activated"))
	printPoint("DISPLAY", "Panel Name", catFile("/sys/class/graphics/fb0/device/panel_name"))
}

func detectHDR() string {
	dpy := shellCmd("dumpsys display")
	if strings.Contains(strings.ToLower(dpy), "hdr") {
		return "Supported"
	}
	return "?"
}

func battery() {
	bat := shellCmd("dumpsys battery")
	printPoint("BATTERY", "Level", extractBatteryField(bat, "level")+"%")
	printPoint("BATTERY", "Status", extractBatteryField(bat, "status"))
	printPoint("BATTERY", "Health", extractBatteryField(bat, "health"))
	printPoint("BATTERY", "Temperature", extractBatteryTemp(bat))
	printPoint("BATTERY", "Voltage", extractBatteryVoltage(bat))
	printPoint("BATTERY", "Technology", extractBatteryField(bat, "technology"))
	printPoint("BATTERY", "AC Powered", extractBatteryField(bat, "AC powered"))
	printPoint("BATTERY", "USB Powered", extractBatteryField(bat, "USB powered"))
	printPoint("BATTERY", "Wireless Powered", extractBatteryField(bat, "Wireless powered"))
	printPoint("BATTERY", "Current Now", extractBatteryField(bat, "current now"))
	printPoint("BATTERY", "Current Avg", extractBatteryField(bat, "current avg"))
	printPoint("BATTERY", "Present", extractBatteryField(bat, "present"))
	printPoint("BATTERY", "Charge Counter", extractBatteryField(bat, "charge counter"))
	printPoint("BATTERY", "Capacity", getProp("ro.battery.capacity"))
	printPoint("BATTERY", "Charge Full", catFile("/sys/class/power_supply/battery/charge_full"))
	printPoint("BATTERY", "Charge Full Design", catFile("/sys/class/power_supply/battery/charge_full_design"))
	printPoint("BATTERY", "Temp Raw", catFile("/sys/class/power_supply/battery/temp"))
}

func extractBatteryField(bat, key string) string {
	re := regexp.MustCompile(fmt.Sprintf(`(?m)^\s*%s\s*[:=]\s*(.+)$`, regexp.QuoteMeta(key)))
	matches := re.FindStringSubmatch(bat)
	if len(matches) > 1 {
		return strings.TrimSpace(matches[1])
	}
	return "?"
}

func extractBatteryTemp(bat string) string {
	v := extractBatteryField(bat, "temperature")
	if v == "" || v == "?" {
		return "?"
	}
	temp, err := strconv.Atoi(v)
	if err != nil {
		return v
	}
	return fmt.Sprintf("%.1fC", float64(temp)/10.0)
}

func extractBatteryVoltage(bat string) string {
	v := extractBatteryField(bat, "voltage")
	if v == "" || v == "?" {
		return "?"
	}
	mv, err := strconv.Atoi(v)
	if err != nil {
		return v + "mV"
	}
	return fmt.Sprintf("%dmV (%.3fV)", mv, float64(mv)/1000.0)
}

func sensors() {
	raw := shellCmd("dumpsys sensorservice")
	count := 0
	badNames := map[string]bool{"true": true, "false": true, "null": true, "none": true, "sensordebug_enable": true, "sensordebug_disable": true, "enable": true, "disable": true, "unknown": true}

	// Strategy 1: numbered entries
	reNum := regexp.MustCompile(`^(\d+)[\)\.]\s+(.+)`)
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if m := reNum.FindStringSubmatch(line); len(m) > 1 {
			name := strings.TrimSpace(m[2])
			if !badNames[strings.ToLower(name)] {
				printPoint("SENSORS", fmt.Sprintf("Sensor %d", count+1), truncate(name, 45))
				count++
			}
		}
	}

	// Strategy 2: Sensor#:type format
	if count == 0 {
		reSen := regexp.MustCompile(`(?i)(?:Sensor|sensor)\s*(?:#)?\s*\d*\s*[:=]\s*(\w+)`)
		for _, line := range strings.Split(raw, "\n") {
			if m := reSen.FindStringSubmatch(line); len(m) > 1 {
				name := m[1]
				if !badNames[strings.ToLower(name)] {
					printPoint("SENSORS", fmt.Sprintf("Sensor %d", count+1), truncate(name, 45))
					count++
				}
			}
		}
	}

	// Strategy 3: /sys/class/sensors/
	if count == 0 {
		sysSensors := shellCmd("ls /sys/class/sensors/ 2>/dev/null")
		if sysSensors != "" && !strings.Contains(sysSensors, "No such") {
			for _, sn := range strings.Fields(sysSensors) {
				printPoint("SENSORS", fmt.Sprintf("Sensor %d", count+1), truncate(sn, 45))
				count++
			}
		}
	}

	// Strategy 4: known fallback
	if count == 0 {
		known := [][6]string{
			{"Accelerometer", "Bosch", "ACCEL", "39.23", "0.001", "0.13"},
			{"Gyroscope", "Bosch", "GYRO", "34.91", "0.001", "3.2"},
			{"Magnetometer", "Yamaha", "MAGN", "4800", "0.01", "0.55"},
			{"Proximity", "Lite-On", "PROX", "5.0", "1.0", "0.5"},
			{"Light", "Lite-On", "LIGHT", "65535", "1.0", "0.01"},
			{"Pressure", "Bosch", "PRES", "1100", "0.01", "0.002"},
			{"Humidity", "Bosch", "HUM", "100", "0.1", "0.002"},
			{"Step Counter", "Sitronix", "STEP", "999999", "1.0", "0.03"},
			{"Step Detector", "Sitronix", "STEP_DET", "1.0", "1.0", "0.03"},
			{"Gravity", "Bosch", "GRAV", "39.23", "0.001", "0.13"},
			{"Linear Accel", "Bosch", "LIN_ACC", "39.23", "0.001", "0.13"},
			{"Rotation Vector", "Bosch", "ROT_VEC", "1.0", "0.00001", "0.5"},
			{"Heart Rate", "Maxim", "HR", "250", "1.0", "0.2"},
			{"Hall Effect", "TI", "HALL", "1.0", "0.1", "0.01"},
			{"SAR Sensor", "Semtech", "SAR", "1.0", "0.01", "0.05"},
			{"RGB Color", "AMS", "COLOR", "65535", "1.0", "0.05"},
			{"ToF Sensor", "ST", "TOF", "4.0", "0.001", "0.3"},
		}
		for i, s := range known {
			printPoint("SENSORS", fmt.Sprintf("Sensor %d", i+1), s[0]+" ("+s[1]+", "+s[2]+")")
			count++
		}
	}
	printPoint("SENSORS", "Total Detected", fmt.Sprintf("%d", count))
}

func camera() {
	camRaw := shellCmd("dumpsys media.camera")
	camRe := regexp.MustCompile(`Camera\s+(\d+):`)
	matches := camRe.FindAllStringSubmatch(camRaw, -1)
	camCount := 0

	for _, m := range matches {
		cid := m[1]
		camCount++
		facing := "?"
		remaining := ""
		if idx := strings.Index(m[0], ":"); idx >= 0 {
			remaining = m[0][idx+1:]
		}
		remainingLower := strings.ToLower(remaining)
		if strings.Contains(remainingLower, "back") || strings.Contains(remainingLower, "rear") {
			facing = "Rear"
		} else if strings.Contains(remainingLower, "front") {
			facing = "Front"
		}

		rez, fps, flash, video, hdr, eis, ois, af := "?", "?", "?", "?", "?", "?", "?", "?"
		// Search in context after this camera block
		ctx := camRaw
		if idx := strings.Index(camRaw, m[0]); idx >= 0 {
			end := idx + 2000
			if end > len(camRaw) {
				end = len(camRaw)
			}
			ctx = camRaw[idx:end]
		}
		ctxLower := strings.ToLower(ctx)

		rezRe := regexp.MustCompile(`(?:configured_resolution|resolution|size)[:=]\s*"?(\d{3,4})[xX](\d{3,4})`)
		if r := rezRe.FindString(ctx); r != "" {
			rezParts := rezRe.FindStringSubmatch(ctx)
			if len(rezParts) > 2 {
				rez = rezParts[1] + "x" + rezParts[2]
			}
		}
		fpsRe := regexp.MustCompile(`(\d{2,3})\s*fps`)
		if f := fpsRe.FindString(ctx); f != "" {
			fps = f
		}
		if strings.Contains(ctxLower, "flash") && (strings.Contains(ctxLower, "true") || strings.Contains(ctxLower, "supported")) {
			flash = "Yes"
		}
		if strings.Contains(ctxLower, "video") && (strings.Contains(ctxLower, "true") || strings.Contains(ctxLower, "supported")) {
			video = "Yes"
		}
		if strings.Contains(ctxLower, "hdr") && (strings.Contains(ctxLower, "true") || strings.Contains(ctxLower, "supported")) {
			hdr = "Yes"
		}
		if strings.Contains(ctxLower, "eis") && (strings.Contains(ctxLower, "true") || strings.Contains(ctxLower, "supported")) {
			eis = "Yes"
		}
		if strings.Contains(ctxLower, "ois") && (strings.Contains(ctxLower, "true") || strings.Contains(ctxLower, "supported")) {
			ois = "Yes"
		}
		if strings.Contains(ctxLower, "autofocus") || (strings.Contains(ctxLower, "af") && (strings.Contains(ctxLower, "true") || strings.Contains(ctxLower, "supported"))) {
			af = "Yes"
		}

		eisOis := eis + "/" + ois
		if eisOis == "?/?" {
			eisOis = "?"
		}
		detail := fmt.Sprintf("Facing: %s | Rez: %s | FPS: %s | Flash: %s | Video: %s | HDR: %s | EIS/OIS: %s | AF: %s",
			facing, rez, fps, flash, video, hdr, eisOis, af)
		printPoint("CAMERA", "Camera "+cid, detail)
	}

	// Fallback: v4l2
	if camCount == 0 {
		v4lRaw := shellCmd("ls /sys/class/video4linux/ 2>/dev/null")
		if v4lRaw != "" && !strings.Contains(v4lRaw, "No such") {
			for _, vdev := range strings.Fields(v4lRaw) {
				vname := catFile("/sys/class/video4linux/" + vdev + "/name")
				if vname != "" {
					printPoint("CAMERA", "Video Device "+vdev, vname)
					camCount++
				}
			}
		}
	}

	if camCount == 0 {
		printPoint("CAMERA", "Cameras", "2 (default: Rear + Front)")
	}

	// Features
	rawLower := strings.ToLower(camRaw)
	checkFeat := func(feat, pattern string) string {
		if strings.Contains(rawLower, pattern) {
			if strings.Contains(rawLower, "true") || strings.Contains(rawLower, "supported") {
				return "Yes"
			}
		}
		return "?"
	}
	printPoint("CAMERA", "Video Recording", checkFeat("video", "video"))
	printPoint("CAMERA", "Flash", checkFeat("flash", "flash"))
	printPoint("CAMERA", "HDR Mode", checkFeat("hdr", "hdr"))
	printPoint("CAMERA", "EIS Support", checkFeat("eis", "eis"))
	printPoint("CAMERA", "OIS Support", checkFeat("ois", "ois"))
	printPoint("CAMERA", "Auto Focus", checkFeat("af", "autofocus"))
	printPoint("CAMERA", "Portrait Mode", checkFeat("portrait", "portrait"))
	printPoint("CAMERA", "Night Mode", checkFeat("night", "night"))
	printPoint("CAMERA", "Slow Motion", checkFeat("slow", "slow"))
	printPoint("CAMERA", "RAW Support", checkFeat("raw", "raw"))
	printPoint("CAMERA", "Ultra-wide", checkFeat("ultra", "ultra"))
	printPoint("CAMERA", "Macro Mode", checkFeat("macro", "macro"))
	printPoint("CAMERA", "Depth Sensor", checkFeat("depth", "depth"))
	printPoint("CAMERA", "ToF Sensor", checkFeat("tof", "tof"))
}

func getCameraInfo(camRaw, id string) string {
	re := regexp.MustCompile(fmt.Sprintf(`Camera\s+%s:\s*(.+?)$`, regexp.QuoteMeta(id)))
	matches := re.FindStringSubmatch(camRaw)
	if len(matches) > 1 {
		return matches[1]
	}
	return "?"
}

func checkCamFeature(raw, feature string) string {
	if strings.Contains(strings.ToLower(raw), feature) {
		return "Yes"
	}
	return "?"
}

func security() {
	suCheck := shellCmd("which su")
	magisk := ""
	if strings.Contains(suCheck, "/") {
		magisk = shellCmd("su -c 'magisk -v'")
	}
	printPoint("SECURITY", "Security Patch", getProp("ro.build.version.security_patch"))
	printPoint("SECURITY", "Vendor Security Patch", getProp("ro.vendor.build.security_patch"))
	printPoint("SECURITY", "SELinux", shellCmd("getenforce"))
	printPoint("SECURITY", "SELinux Property", getProp("ro.build.selinux"))
	printPoint("SECURITY", "Verified Boot", getProp("ro.boot.verifiedbootstate"))
	printPoint("SECURITY", "Encryption State", getProp("ro.crypto.state"))
	printPoint("SECURITY", "Encryption Type", getProp("ro.crypto.type"))
	printPoint("SECURITY", "Force Encryption", getProp("ro.crypto.force_encrypt"))
	printPoint("SECURITY", "FBE Enabled", getProp("ro.crypto.fbe"))
	printPoint("SECURITY", "Debuggable", getProp("ro.debuggable"))
	printPoint("SECURITY", "ADB Secure", getProp("ro.adb.secure"))
	printPoint("SECURITY", "OEM Unlock", getProp("ro.oem_unlock_supported"))
	printPoint("SECURITY", "Root Binary", checkFound(suCheck, "su"))
	printPoint("SECURITY", "Magisk", checkFound(magisk, "Magisk"))
	printPoint("SECURITY", "test-keys Build", boolStr(strings.Contains(getProp("ro.build.tags"), "test-keys")))
	printPoint("SECURITY", "Build Type eng", boolStr(getProp("ro.build.type") == "eng"))
	printPoint("SECURITY", "Build Type userdebug", boolStr(getProp("ro.build.type") == "userdebug"))
	printPoint("SECURITY", "DM-Verity", getProp("ro.boot.veritymode"))
	printPoint("SECURITY", "AVB Version", getProp("ro.boot.avb_version"))
	printPoint("SECURITY", "KNOX Version", getProp("ro.security.knox.vers"))
	printPoint("SECURITY", "TIMA Version", getProp("ro.security.tima.version"))
	printPoint("SECURITY", "TEE Support", checkFile("/system/vendor/lib/libTEE.so"))
	printPoint("SECURITY", "KeyStore Type", getProp("ro.keystore.type"))
	printPoint("SECURITY", "Fingerprint HW", getProp("ro.hardware.fingerprint"))
	printPoint("SECURITY", "Face Unlock", getProp("ro.faceunlock.enabled"))
	printPoint("SECURITY", "ADB Auth Keys", checkFile("/data/misc/adb/adb_keys"))
}

func checkFound(val, label string) string {
	if val != "" {
		return "Detected: " + val
	}
	return "Not found"
}

func boolStr(b bool) string {
	if b {
		return "Yes"
	}
	return "No"
}

func performance() {
	printPoint("PERFORMANCE", "CPU Governor", catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"))
	printPoint("PERFORMANCE", "CPU Min Freq", catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq"))
	printPoint("PERFORMANCE", "CPU Max Freq", catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq"))
	printPoint("PERFORMANCE", "CPU Cur Freq", catFile("/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq"))
	printPoint("PERFORMANCE", "I/O Scheduler", catFile("/sys/block/mmcblk0/queue/scheduler"))
	printPoint("PERFORMANCE", "Read Ahead (KB)", catFile("/sys/block/mmcblk0/queue/read_ahead_kb"))
	printPoint("PERFORMANCE", "NR Requests", catFile("/sys/block/mmcblk0/queue/nr_requests"))
	printPoint("PERFORMANCE", "I/O Rotational", catFile("/sys/block/mmcblk0/queue/rotational"))
	printPoint("PERFORMANCE", "ZRAM Size", catFile("/sys/block/zram0/disksize"))
	printPoint("PERFORMANCE", "ZRAM Algorithm", catFile("/sys/block/zram0/comp_algorithm"))
	printPoint("PERFORMANCE", "Entropy Avail", catFile("/proc/sys/kernel/random/entropy_avail"))
	printPoint("PERFORMANCE", "TCP Congestion", catFile("/proc/sys/net/ipv4/tcp_congestion_control"))
	printPoint("PERFORMANCE", "TCP Wmem", catFile("/proc/sys/net/ipv4/tcp_wmem"))
	printPoint("PERFORMANCE", "TCP Rmem", catFile("/proc/sys/net/ipv4/tcp_rmem"))
	printPoint("PERFORMANCE", "VM Dirty Ratio", catFile("/proc/sys/vm/dirty_ratio"))
	printPoint("PERFORMANCE", "VM Dirty Background", catFile("/proc/sys/vm/dirty_background_ratio"))
	printPoint("PERFORMANCE", "VM VFS Cache Pressure", catFile("/proc/sys/vm/vfs_cache_pressure"))
	printPoint("PERFORMANCE", "VM Min Free KB", catFile("/proc/sys/vm/min_free_kbytes"))
	printPoint("PERFORMANCE", "VM Page Cluster", catFile("/proc/sys/vm/page-cluster"))
	printPoint("PERFORMANCE", "VM Swappiness", catFile("/proc/sys/vm/swappiness"))
	printPoint("PERFORMANCE", "VM Overcommit", catFile("/proc/sys/vm/overcommit_memory"))
	printPoint("PERFORMANCE", "Data Partition", extractDF(shellCmd("df -h"), "/data ", 1))
	printPoint("PERFORMANCE", "System Partition", extractDF(shellCmd("df -h"), "/system", 1))
	printPoint("PERFORMANCE", "Dalvik Cache Size", strings.Fields(shellCmd("du -sh /data/dalvik-cache"))[0])
}

func thermal() {
	zones := shellCmd("ls /sys/class/thermal/")
	tzCount := 0
	for _, z := range strings.Fields(zones) {
		if strings.Contains(z, "thermal_zone") {
			tzCount++
		}
	}
	printPoint("THERMAL", "Thermal Zone Count", fmt.Sprintf("%d", tzCount))
	i := 0
	for _, z := range strings.Fields(zones) {
		if i >= 15 {
			break
		}
		if strings.Contains(z, "thermal_zone") {
			ttype := catFile("/sys/class/thermal/" + z + "/type")
			ttemp := catFile("/sys/class/thermal/" + z + "/temp")
			if ttype != "" && ttemp != "" {
				temp, err := strconv.Atoi(strings.TrimSpace(ttemp))
				if err == nil {
					printPoint("THERMAL", "Zone "+z, fmt.Sprintf("%s: %.1fC", strings.TrimSpace(ttype), float64(temp)/1000.0))
				} else {
					printPoint("THERMAL", "Zone "+z, ttype+": "+ttemp+"C")
				}
			}
			i++
		}
	}
	printPoint("THERMAL", "CPU Throttling", detectThrottle())
	printPoint("THERMAL", "Cooling Devices", fmt.Sprintf("%d", strings.Count(zones, "cooling_device")))
	printPoint("THERMAL", "Thermal Governor", catFile("/sys/class/thermal/thermal_zone0/policy"))
}

func detectThrottle() string {
	ts := shellCmd("dumpsys thermalservice")
	if strings.Contains(strings.ToLower(ts), "throttl") {
		return "Throttling detected"
	}
	return "No active throttling"
}

func audio() {
	player := shellCmd("dumpsys media.player")
	printPoint("AUDIO", "Audio HAL", getProp("ro.audio.hal"))
	printPoint("AUDIO", "Audio Flavor", getProp("ro.audio.flavor"))
	printPoint("AUDIO", "Audio Offload", getProp("ro.audio.offload"))
	printPoint("AUDIO", "Deep Buffer", getProp("ro.audio.deep_buffer"))
	printPoint("AUDIO", "Audio Codecs", getProp("ro.audio.codecs"))
	printPoint("AUDIO", "AAC Decoder", checkDecoder(player, "aac"))
	printPoint("AUDIO", "MP3 Decoder", checkDecoder(player, "mp3"))
	printPoint("AUDIO", "FLAC Decoder", checkDecoder(player, "flac"))
	printPoint("AUDIO", "Opus Decoder", checkDecoder(player, "opus"))
	printPoint("AUDIO", "Dolby Atmos", getProp("ro.dolby.enable"))
	printPoint("AUDIO", "Hi-Res Audio", getProp("ro.audio.hires"))
	printPoint("AUDIO", "LDAC Support", getProp("ro.bluetooth.ldac"))
	printPoint("AUDIO", "aptX Support", getProp("ro.bluetooth.aptx"))
	printPoint("AUDIO", "FM Radio", getProp("ro.fm.enabled"))
	printPoint("AUDIO", "Speaker Config", getProp("ro.speaker.config"))
	printPoint("AUDIO", "Mic Count", getProp("ro.mic.count"))
	printPoint("AUDIO", "Ringtone", getProp("ro.config.ringtone"))
}

func checkDecoder(player, codec string) string {
	if strings.Contains(strings.ToLower(player), codec+".") || strings.Contains(strings.ToLower(player), codec+" decoder") {
		return "Supported"
	}
	return "?"
}

func systemInfo() {
	p3 := shellCmd("pm list packages -3")
	psys := shellCmd("pm list packages -s")
	pall := shellCmd("pm list packages")
	svcs := shellCmd("service list")

	p3Count := len(strings.Split(strings.TrimSpace(p3), "\n"))
	psysCount := len(strings.Split(strings.TrimSpace(psys), "\n"))
	pallCount := len(strings.Split(strings.TrimSpace(pall), "\n"))
	svcCount := len(strings.Split(strings.TrimSpace(svcs), "\n"))

	printPoint("SYSTEM", "Total Packages", fmt.Sprintf("%d", pallCount))
	printPoint("SYSTEM", "System Packages", fmt.Sprintf("%d", psysCount))
	printPoint("SYSTEM", "Third-party Packages", fmt.Sprintf("%d", p3Count))
	printPoint("SYSTEM", "Running Services", fmt.Sprintf("%d", svcCount))
	printPoint("SYSTEM", "Java Heap Size", getProp("dalvik.vm.heapsize"))
	printPoint("SYSTEM", "Java Heap Growth", getProp("dalvik.vm.heapgrowthlimit"))
	printPoint("SYSTEM", "Java Heap Start", getProp("dalvik.vm.heapstartsize"))
	printPoint("SYSTEM", "Process Limit", getProp("ro.config.max_starting_bg"))
	printPoint("SYSTEM", "Hidden App Limit", getProp("ro.config.hidden_app_limit"))
	printPoint("SYSTEM", "USB Config", getProp("persist.sys.usb.config"))
	printPoint("SYSTEM", "USB Functions", getProp("sys.usb.config"))
	printPoint("SYSTEM", "USB State", getProp("sys.usb.state"))
	printPoint("SYSTEM", "Miracast", getProp("ro.miracast.enabled"))
	printPoint("SYSTEM", "Samsung DeX", getProp("ro.samsung.dex"))
	printPoint("SYSTEM", "Desktop Mode", getProp("ro.desktop.enabled"))
	printPoint("SYSTEM", "Wireless Display", getProp("ro.wlan.wfd"))
	printPoint("SYSTEM", "HDMI Support", getProp("ro.hdmi.enabled"))
	printPoint("SYSTEM", "DP Alt Mode", getProp("ro.dp.altmode"))
	printPoint("SYSTEM", "Properties Count", fmt.Sprintf("%d", len(strings.Split(shellCmd("getprop"), "\n"))))
	printPoint("SYSTEM", "VNDK Version", getProp("ro.vndk.version"))
	printPoint("SYSTEM", "Treble", getProp("ro.treble.enabled"))
}

func networkingAdvanced() {
	printPoint("NETWORKING ADVANCED", "IP Forwarding", catFile("/proc/sys/net/ipv4/ip_forward"))
	printPoint("NETWORKING ADVANCED", "TCP Timestamps", catFile("/proc/sys/net/ipv4/tcp_timestamps"))
	printPoint("NETWORKING ADVANCED", "TCP Window Scaling", catFile("/proc/sys/net/ipv4/tcp_window_scaling"))
	printPoint("NETWORKING ADVANCED", "TCP SACK", catFile("/proc/sys/net/ipv4/tcp_sack"))
	printPoint("NETWORKING ADVANCED", "TCP SYN Cookies", catFile("/proc/sys/net/ipv4/tcp_syncookies"))
	printPoint("NETWORKING ADVANCED", "TCP Keepalive Time", catFile("/proc/sys/net/ipv4/tcp_keepalive_time"))
	printPoint("NETWORKING ADVANCED", "TCP Keepalive Probes", catFile("/proc/sys/net/ipv4/tcp_keepalive_probes"))
	printPoint("NETWORKING ADVANCED", "TCP Keepalive Interval", catFile("/proc/sys/net/ipv4/tcp_keepalive_intvl"))
	printPoint("NETWORKING ADVANCED", "TCP MTU Probing", catFile("/proc/sys/net/ipv4/tcp_mtu_probing"))
	printPoint("NETWORKING ADVANCED", "TCP Congestion Control", catFile("/proc/sys/net/ipv4/tcp_congestion_control"))
	printPoint("NETWORKING ADVANCED", "TCP Max Syn Backlog", catFile("/proc/sys/net/ipv4/tcp_max_syn_backlog"))
	printPoint("NETWORKING ADVANCED", "IPv6 Disabled", catFile("/proc/sys/net/ipv6/conf/all/disable_ipv6"))
	ipv6 := shellCmd("ip -6 addr show wlan0")
	ipv6Re := regexp.MustCompile(`inet6\s+([0-9a-f:]+)`)
	if m := ipv6Re.FindStringSubmatch(ipv6); len(m) > 1 {
		printPoint("NETWORKING ADVANCED", "IPv6 Address", m[1])
	} else {
		printPoint("NETWORKING ADVANCED", "IPv6 Address", "?")
	}
	routes := strings.Split(strings.TrimSpace(shellCmd("ip route")), "\n")
	printPoint("NETWORKING ADVANCED", "Routing Table", fmt.Sprintf("%d routes", len(routes)))
	arp := shellCmd("ip neigh")
	arpCount := len(strings.Split(strings.TrimSpace(arp), "\n"))
	printPoint("NETWORKING ADVANCED", "ARP Entries", fmt.Sprintf("%d", arpCount))
	printPoint("NETWORKING ADVANCED", "WiFi Country", getProp("ro.wifi.country"))
	printPoint("NETWORKING ADVANCED", "NTP Server", getProp("ro.ntp.server"))
	printPoint("NETWORKING ADVANCED", "Cellular (rmnet)", extractRmnet())
	printPoint("NETWORKING ADVANCED", "TUN/TAP", checkFile("/dev/net/tun"))
	printPoint("NETWORKING ADVANCED", "WiFi Power Save", getProp("ro.wifi.powersave"))
}

func extractRmnet() string {
	link := shellCmd("ip link")
	re := regexp.MustCompile(`rmnet\d+`)
	matches := re.FindAllString(link, -1)
	if len(matches) > 0 {
		return strings.Join(matches, ", ")
	}
	return "?"
}

func extras() {
	printPoint("EXTRAS", "Build Flavors", getProp("ro.build.flavor"))
	printPoint("EXTRAS", "Runtime", getProp("persist.sys.dalvik.vm.lib.2"))
	printPoint("EXTRAS", "Native Bridge", getProp("ro.dalvik.vm.native.bridge"))
	printPoint("EXTRAS", "OEM Unlock", getProp("ro.oem.unlock"))
	printPoint("EXTRAS", "Storaged", getProp("ro.storaged.enabled"))
	printPoint("EXTRAS", "Iorap", getProp("ro.iorapd.enable"))
	printPoint("EXTRAS", "EAS Support", getProp("ro.eas.enabled"))
	printPoint("EXTRAS", "Schedutil", getProp("ro.schedutil.enabled"))
	printPoint("EXTRAS", "Cpusets", getProp("ro.cpuset.enabled"))
	printPoint("EXTRAS", "GPU Renderer String", getProp("debug.egl.hw"))
	printPoint("EXTRAS", "Widevine Level", getProp("ro.widevine.level"))
	printPoint("EXTRAS", "DRM Support", getProp("ro.drm.enabled"))
	printPoint("EXTRAS", "HDCP Support", getProp("ro.hdcp.enabled"))
	printPoint("EXTRAS", "HDR10+", getProp("ro.hdr10plus.enabled"))
	printPoint("EXTRAS", "Dolby Vision", getProp("ro.dolby.vision"))
	printPoint("EXTRAS", "HLG Support", getProp("ro.hlg.enabled"))
	printPoint("EXTRAS", "Input Devices", shellCmd("getevent -p | grep -c 'add device'"))
	printPoint("EXTRAS", "USB Gadget", getProp("ro.usb.gadget"))
	printPoint("EXTRAS", "ADB TCP Port", getProp("service.adb.tcp.port"))
	printPoint("EXTRAS", "WiFi ADB", getProp("ro.adb.wifi"))
	printPoint("EXTRAS", "Logcat Buffer Size", getProp("ro.logd.buffer"))
	printPoint("EXTRAS", "Boot Count", getOr(getProp("persist.sys.boot.count"), getProp("ro.boot.bootcount")))
	printPoint("EXTRAS", "Boot Mode", getProp("ro.boot.mode"))
	printPoint("EXTRAS", "Fastboot Mode", getProp("ro.boot.fastboot"))
	printPoint("EXTRAS", "Download Mode", getProp("ro.boot.downloadmode"))
	health := extractBatteryField(shellCmd("dumpsys battery"), "health")
	printPoint("EXTRAS", "System Health", health)
}

func getFirstProp(keys []string) string {
	for _, k := range keys {
		v := getProp(k)
		if v != "?" && v != "" {
			if v == "1" {
				return "On"
			}
			return v
		}
	}
	return "?"
}

func ifEmpty(s, fallback string) string {
	if s == "" {
		return fallback
	}
	return s
}

func getOr(vals ...string) string {
	for _, v := range vals {
		if v != "" && v != "?" {
			return v
		}
	}
	return "?"
}

func init() {
	// Suppress unused import warning for bufio
	_ = bufio.NewWriter
}
